package at.lame.hellonzb.statistics;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-06T02:52:36.349+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "urn:hellonzb", name = "HelloNzbPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloNzbPortType {

    /**
     * Register new Startup
     */
    @WebResult(name = "startupResponse", targetNamespace = "urn:hellonzb", partName = "parameters")
    @WebMethod(action = "http://hellonzb.sourceforge.net/stats/server.php#startup")
    public StartupResponseType startup(
        @WebParam(partName = "parameters", name = "startup", targetNamespace = "urn:hellonzb")
        StartupRequestType parameters
    );

    /**
     * Register new Download
     */
    @WebResult(name = "downloadResponse", targetNamespace = "urn:hellonzb", partName = "parameters")
    @WebMethod(action = "http://hellonzb.sourceforge.net/stats/server.php#download")
    public DownloadResponseType download(
        @WebParam(partName = "parameters", name = "download", targetNamespace = "urn:hellonzb")
        DownloadRequestType parameters
    );
}
